DEBUG = True

SECRET_KEY = 'CHANGE'

FACEBOOK_APP_ID = 'CHANGE'
FACEBOOK_APP_SECRET = 'CHANGE'

TWITTER_CONSUMER_KEY = 'CHANGE'
TWITTER_CONSUMER_SECRET = 'CHANGE'

GOOGLE_CLIENT_SECRET='CHANGE'
GOOGLE_CLIENT_ID='CHANGE'
